// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.0
// source: api/v1/service.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	WorkflowType  string                 `protobuf:"bytes,2,opt,name=workflow_type,json=workflowType,proto3" json:"workflow_type,omitempty"`
	TaskQueue     string                 `protobuf:"bytes,3,opt,name=task_queue,json=taskQueue,proto3" json:"task_queue,omitempty"`
	Input         []byte                 `protobuf:"bytes,4,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartWorkflowRequest) Reset() {
	*x = StartWorkflowRequest{}
	mi := &file_api_v1_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkflowRequest) ProtoMessage() {}

func (x *StartWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkflowRequest.ProtoReflect.Descriptor instead.
func (*StartWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{0}
}

func (x *StartWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *StartWorkflowRequest) GetWorkflowType() string {
	if x != nil {
		return x.WorkflowType
	}
	return ""
}

func (x *StartWorkflowRequest) GetTaskQueue() string {
	if x != nil {
		return x.TaskQueue
	}
	return ""
}

func (x *StartWorkflowRequest) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

type StartWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartWorkflowResponse) Reset() {
	*x = StartWorkflowResponse{}
	mi := &file_api_v1_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartWorkflowResponse) ProtoMessage() {}

func (x *StartWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartWorkflowResponse.ProtoReflect.Descriptor instead.
func (*StartWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{1}
}

func (x *StartWorkflowResponse) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

type DescribeWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeWorkflowRequest) Reset() {
	*x = DescribeWorkflowRequest{}
	mi := &file_api_v1_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeWorkflowRequest) ProtoMessage() {}

func (x *DescribeWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeWorkflowRequest.ProtoReflect.Descriptor instead.
func (*DescribeWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{2}
}

func (x *DescribeWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

type DescribeWorkflowResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	WorkflowExecution *WorkflowExecution     `protobuf:"bytes,1,opt,name=workflow_execution,json=workflowExecution,proto3" json:"workflow_execution,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *DescribeWorkflowResponse) Reset() {
	*x = DescribeWorkflowResponse{}
	mi := &file_api_v1_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeWorkflowResponse) ProtoMessage() {}

func (x *DescribeWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeWorkflowResponse.ProtoReflect.Descriptor instead.
func (*DescribeWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{3}
}

func (x *DescribeWorkflowResponse) GetWorkflowExecution() *WorkflowExecution {
	if x != nil {
		return x.WorkflowExecution
	}
	return nil
}

type GetWorkflowHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowHistoryRequest) Reset() {
	*x = GetWorkflowHistoryRequest{}
	mi := &file_api_v1_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowHistoryRequest) ProtoMessage() {}

func (x *GetWorkflowHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetWorkflowHistoryRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{4}
}

func (x *GetWorkflowHistoryRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

type GetWorkflowHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*HistoryEvent        `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWorkflowHistoryResponse) Reset() {
	*x = GetWorkflowHistoryResponse{}
	mi := &file_api_v1_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWorkflowHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWorkflowHistoryResponse) ProtoMessage() {}

func (x *GetWorkflowHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWorkflowHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetWorkflowHistoryResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{5}
}

func (x *GetWorkflowHistoryResponse) GetEvents() []*HistoryEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type TerminateWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateWorkflowRequest) Reset() {
	*x = TerminateWorkflowRequest{}
	mi := &file_api_v1_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateWorkflowRequest) ProtoMessage() {}

func (x *TerminateWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateWorkflowRequest.ProtoReflect.Descriptor instead.
func (*TerminateWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{6}
}

func (x *TerminateWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *TerminateWorkflowRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type TerminateWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TerminateWorkflowResponse) Reset() {
	*x = TerminateWorkflowResponse{}
	mi := &file_api_v1_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TerminateWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateWorkflowResponse) ProtoMessage() {}

func (x *TerminateWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TerminateWorkflowResponse.ProtoReflect.Descriptor instead.
func (*TerminateWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{7}
}

type SignalWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	SignalName    string                 `protobuf:"bytes,2,opt,name=signal_name,json=signalName,proto3" json:"signal_name,omitempty"`
	Input         []byte                 `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalWorkflowRequest) Reset() {
	*x = SignalWorkflowRequest{}
	mi := &file_api_v1_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalWorkflowRequest) ProtoMessage() {}

func (x *SignalWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalWorkflowRequest.ProtoReflect.Descriptor instead.
func (*SignalWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{8}
}

func (x *SignalWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *SignalWorkflowRequest) GetSignalName() string {
	if x != nil {
		return x.SignalName
	}
	return ""
}

func (x *SignalWorkflowRequest) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

type SignalWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignalWorkflowResponse) Reset() {
	*x = SignalWorkflowResponse{}
	mi := &file_api_v1_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignalWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignalWorkflowResponse) ProtoMessage() {}

func (x *SignalWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignalWorkflowResponse.ProtoReflect.Descriptor instead.
func (*SignalWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{9}
}

type PollWorkflowTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueName     string                 `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollWorkflowTaskRequest) Reset() {
	*x = PollWorkflowTaskRequest{}
	mi := &file_api_v1_service_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollWorkflowTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollWorkflowTaskRequest) ProtoMessage() {}

func (x *PollWorkflowTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollWorkflowTaskRequest.ProtoReflect.Descriptor instead.
func (*PollWorkflowTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{10}
}

func (x *PollWorkflowTaskRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *PollWorkflowTaskRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type PollWorkflowTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	WorkflowType  string                 `protobuf:"bytes,3,opt,name=workflow_type,json=workflowType,proto3" json:"workflow_type,omitempty"`
	Events        []*HistoryEvent        `protobuf:"bytes,4,rep,name=events,proto3" json:"events,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollWorkflowTaskResponse) Reset() {
	*x = PollWorkflowTaskResponse{}
	mi := &file_api_v1_service_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollWorkflowTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollWorkflowTaskResponse) ProtoMessage() {}

func (x *PollWorkflowTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollWorkflowTaskResponse.ProtoReflect.Descriptor instead.
func (*PollWorkflowTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{11}
}

func (x *PollWorkflowTaskResponse) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *PollWorkflowTaskResponse) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *PollWorkflowTaskResponse) GetWorkflowType() string {
	if x != nil {
		return x.WorkflowType
	}
	return ""
}

func (x *PollWorkflowTaskResponse) GetEvents() []*HistoryEvent {
	if x != nil {
		return x.Events
	}
	return nil
}

type CompleteWorkflowTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Commands      []*Command             `protobuf:"bytes,2,rep,name=commands,proto3" json:"commands,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteWorkflowTaskRequest) Reset() {
	*x = CompleteWorkflowTaskRequest{}
	mi := &file_api_v1_service_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteWorkflowTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteWorkflowTaskRequest) ProtoMessage() {}

func (x *CompleteWorkflowTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteWorkflowTaskRequest.ProtoReflect.Descriptor instead.
func (*CompleteWorkflowTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{12}
}

func (x *CompleteWorkflowTaskRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *CompleteWorkflowTaskRequest) GetCommands() []*Command {
	if x != nil {
		return x.Commands
	}
	return nil
}

type CompleteWorkflowTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteWorkflowTaskResponse) Reset() {
	*x = CompleteWorkflowTaskResponse{}
	mi := &file_api_v1_service_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteWorkflowTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteWorkflowTaskResponse) ProtoMessage() {}

func (x *CompleteWorkflowTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteWorkflowTaskResponse.ProtoReflect.Descriptor instead.
func (*CompleteWorkflowTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{13}
}

type FailWorkflowTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Cause         string                 `protobuf:"bytes,2,opt,name=cause,proto3" json:"cause,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailWorkflowTaskRequest) Reset() {
	*x = FailWorkflowTaskRequest{}
	mi := &file_api_v1_service_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailWorkflowTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailWorkflowTaskRequest) ProtoMessage() {}

func (x *FailWorkflowTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailWorkflowTaskRequest.ProtoReflect.Descriptor instead.
func (*FailWorkflowTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{14}
}

func (x *FailWorkflowTaskRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *FailWorkflowTaskRequest) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

func (x *FailWorkflowTaskRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type FailWorkflowTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailWorkflowTaskResponse) Reset() {
	*x = FailWorkflowTaskResponse{}
	mi := &file_api_v1_service_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailWorkflowTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailWorkflowTaskResponse) ProtoMessage() {}

func (x *FailWorkflowTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailWorkflowTaskResponse.ProtoReflect.Descriptor instead.
func (*FailWorkflowTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{15}
}

type PollActivityTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueueName     string                 `protobuf:"bytes,1,opt,name=queue_name,json=queueName,proto3" json:"queue_name,omitempty"`
	WorkerId      string                 `protobuf:"bytes,2,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollActivityTaskRequest) Reset() {
	*x = PollActivityTaskRequest{}
	mi := &file_api_v1_service_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollActivityTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollActivityTaskRequest) ProtoMessage() {}

func (x *PollActivityTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollActivityTaskRequest.ProtoReflect.Descriptor instead.
func (*PollActivityTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{16}
}

func (x *PollActivityTaskRequest) GetQueueName() string {
	if x != nil {
		return x.QueueName
	}
	return ""
}

func (x *PollActivityTaskRequest) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type PollActivityTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	ActivityType  string                 `protobuf:"bytes,3,opt,name=activity_type,json=activityType,proto3" json:"activity_type,omitempty"`
	ActivityInput []byte                 `protobuf:"bytes,4,opt,name=activity_input,json=activityInput,proto3" json:"activity_input,omitempty"`
	Attempt       int32                  `protobuf:"varint,5,opt,name=attempt,proto3" json:"attempt,omitempty"`
	ScheduledAt   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=scheduled_at,json=scheduledAt,proto3" json:"scheduled_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PollActivityTaskResponse) Reset() {
	*x = PollActivityTaskResponse{}
	mi := &file_api_v1_service_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PollActivityTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PollActivityTaskResponse) ProtoMessage() {}

func (x *PollActivityTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PollActivityTaskResponse.ProtoReflect.Descriptor instead.
func (*PollActivityTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{17}
}

func (x *PollActivityTaskResponse) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *PollActivityTaskResponse) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *PollActivityTaskResponse) GetActivityType() string {
	if x != nil {
		return x.ActivityType
	}
	return ""
}

func (x *PollActivityTaskResponse) GetActivityInput() []byte {
	if x != nil {
		return x.ActivityInput
	}
	return nil
}

func (x *PollActivityTaskResponse) GetAttempt() int32 {
	if x != nil {
		return x.Attempt
	}
	return 0
}

func (x *PollActivityTaskResponse) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ScheduledAt
	}
	return nil
}

type CompleteActivityTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Result        []byte                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteActivityTaskRequest) Reset() {
	*x = CompleteActivityTaskRequest{}
	mi := &file_api_v1_service_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteActivityTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteActivityTaskRequest) ProtoMessage() {}

func (x *CompleteActivityTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteActivityTaskRequest.ProtoReflect.Descriptor instead.
func (*CompleteActivityTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{18}
}

func (x *CompleteActivityTaskRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *CompleteActivityTaskRequest) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

type CompleteActivityTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteActivityTaskResponse) Reset() {
	*x = CompleteActivityTaskResponse{}
	mi := &file_api_v1_service_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteActivityTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteActivityTaskResponse) ProtoMessage() {}

func (x *CompleteActivityTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteActivityTaskResponse.ProtoReflect.Descriptor instead.
func (*CompleteActivityTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{19}
}

type FailActivityTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Failure       *ActivityFailure       `protobuf:"bytes,2,opt,name=failure,proto3" json:"failure,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailActivityTaskRequest) Reset() {
	*x = FailActivityTaskRequest{}
	mi := &file_api_v1_service_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailActivityTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailActivityTaskRequest) ProtoMessage() {}

func (x *FailActivityTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailActivityTaskRequest.ProtoReflect.Descriptor instead.
func (*FailActivityTaskRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{20}
}

func (x *FailActivityTaskRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *FailActivityTaskRequest) GetFailure() *ActivityFailure {
	if x != nil {
		return x.Failure
	}
	return nil
}

type FailActivityTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailActivityTaskResponse) Reset() {
	*x = FailActivityTaskResponse{}
	mi := &file_api_v1_service_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailActivityTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailActivityTaskResponse) ProtoMessage() {}

func (x *FailActivityTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailActivityTaskResponse.ProtoReflect.Descriptor instead.
func (*FailActivityTaskResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{21}
}

type CancelWorkflowRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowId    string                 `protobuf:"bytes,1,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelWorkflowRequest) Reset() {
	*x = CancelWorkflowRequest{}
	mi := &file_api_v1_service_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelWorkflowRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelWorkflowRequest) ProtoMessage() {}

func (x *CancelWorkflowRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelWorkflowRequest.ProtoReflect.Descriptor instead.
func (*CancelWorkflowRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{22}
}

func (x *CancelWorkflowRequest) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

type CancelWorkflowResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelWorkflowResponse) Reset() {
	*x = CancelWorkflowResponse{}
	mi := &file_api_v1_service_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelWorkflowResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelWorkflowResponse) ProtoMessage() {}

func (x *CancelWorkflowResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelWorkflowResponse.ProtoReflect.Descriptor instead.
func (*CancelWorkflowResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{23}
}

type RecordActivityHeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        int64                  `protobuf:"varint,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Details       []byte                 `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordActivityHeartbeatRequest) Reset() {
	*x = RecordActivityHeartbeatRequest{}
	mi := &file_api_v1_service_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordActivityHeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordActivityHeartbeatRequest) ProtoMessage() {}

func (x *RecordActivityHeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordActivityHeartbeatRequest.ProtoReflect.Descriptor instead.
func (*RecordActivityHeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{24}
}

func (x *RecordActivityHeartbeatRequest) GetTaskId() int64 {
	if x != nil {
		return x.TaskId
	}
	return 0
}

func (x *RecordActivityHeartbeatRequest) GetDetails() []byte {
	if x != nil {
		return x.Details
	}
	return nil
}

type RecordActivityHeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordActivityHeartbeatResponse) Reset() {
	*x = RecordActivityHeartbeatResponse{}
	mi := &file_api_v1_service_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordActivityHeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordActivityHeartbeatResponse) ProtoMessage() {}

func (x *RecordActivityHeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_service_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordActivityHeartbeatResponse.ProtoReflect.Descriptor instead.
func (*RecordActivityHeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_api_v1_service_proto_rawDescGZIP(), []int{25}
}

var File_api_v1_service_proto protoreflect.FileDescriptor

const file_api_v1_service_proto_rawDesc = "" +
	"\n" +
	"\x14api/v1/service.proto\x12\x0edandori.api.v1\x1a\x12api/v1/types.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x91\x01\n" +
	"\x14StartWorkflowRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12#\n" +
	"\rworkflow_type\x18\x02 \x01(\tR\fworkflowType\x12\x1d\n" +
	"\n" +
	"task_queue\x18\x03 \x01(\tR\ttaskQueue\x12\x14\n" +
	"\x05input\x18\x04 \x01(\fR\x05input\"8\n" +
	"\x15StartWorkflowResponse\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\":\n" +
	"\x17DescribeWorkflowRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\"l\n" +
	"\x18DescribeWorkflowResponse\x12P\n" +
	"\x12workflow_execution\x18\x01 \x01(\v2!.dandori.api.v1.WorkflowExecutionR\x11workflowExecution\"<\n" +
	"\x19GetWorkflowHistoryRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\"R\n" +
	"\x1aGetWorkflowHistoryResponse\x124\n" +
	"\x06events\x18\x01 \x03(\v2\x1c.dandori.api.v1.HistoryEventR\x06events\"S\n" +
	"\x18TerminateWorkflowRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x1b\n" +
	"\x19TerminateWorkflowResponse\"o\n" +
	"\x15SignalWorkflowRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\x12\x1f\n" +
	"\vsignal_name\x18\x02 \x01(\tR\n" +
	"signalName\x12\x14\n" +
	"\x05input\x18\x03 \x01(\fR\x05input\"\x18\n" +
	"\x16SignalWorkflowResponse\"U\n" +
	"\x17PollWorkflowTaskRequest\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tR\tqueueName\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\"\xaf\x01\n" +
	"\x18PollWorkflowTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12#\n" +
	"\rworkflow_type\x18\x03 \x01(\tR\fworkflowType\x124\n" +
	"\x06events\x18\x04 \x03(\v2\x1c.dandori.api.v1.HistoryEventR\x06events\"k\n" +
	"\x1bCompleteWorkflowTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x123\n" +
	"\bcommands\x18\x02 \x03(\v2\x17.dandori.api.v1.CommandR\bcommands\"\x1e\n" +
	"\x1cCompleteWorkflowTaskResponse\"b\n" +
	"\x17FailWorkflowTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12\x14\n" +
	"\x05cause\x18\x02 \x01(\tR\x05cause\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"\x1a\n" +
	"\x18FailWorkflowTaskResponse\"U\n" +
	"\x17PollActivityTaskRequest\x12\x1d\n" +
	"\n" +
	"queue_name\x18\x01 \x01(\tR\tqueueName\x12\x1b\n" +
	"\tworker_id\x18\x02 \x01(\tR\bworkerId\"\xf9\x01\n" +
	"\x18PollActivityTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12#\n" +
	"\ractivity_type\x18\x03 \x01(\tR\factivityType\x12%\n" +
	"\x0eactivity_input\x18\x04 \x01(\fR\ractivityInput\x12\x18\n" +
	"\aattempt\x18\x05 \x01(\x05R\aattempt\x12=\n" +
	"\fscheduled_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\"N\n" +
	"\x1bCompleteActivityTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12\x16\n" +
	"\x06result\x18\x02 \x01(\fR\x06result\"\x1e\n" +
	"\x1cCompleteActivityTaskResponse\"m\n" +
	"\x17FailActivityTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x129\n" +
	"\afailure\x18\x02 \x01(\v2\x1f.dandori.api.v1.ActivityFailureR\afailure\"\x1a\n" +
	"\x18FailActivityTaskResponse\"8\n" +
	"\x15CancelWorkflowRequest\x12\x1f\n" +
	"\vworkflow_id\x18\x01 \x01(\tR\n" +
	"workflowId\"\x18\n" +
	"\x16CancelWorkflowResponse\"S\n" +
	"\x1eRecordActivityHeartbeatRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\x03R\x06taskId\x12\x18\n" +
	"\adetails\x18\x02 \x01(\fR\adetails\"!\n" +
	"\x1fRecordActivityHeartbeatResponse2\xec\n" +
	"\n" +
	"\x0eDandoriService\x12\\\n" +
	"\rStartWorkflow\x12$.dandori.api.v1.StartWorkflowRequest\x1a%.dandori.api.v1.StartWorkflowResponse\x12e\n" +
	"\x10DescribeWorkflow\x12'.dandori.api.v1.DescribeWorkflowRequest\x1a(.dandori.api.v1.DescribeWorkflowResponse\x12k\n" +
	"\x12GetWorkflowHistory\x12).dandori.api.v1.GetWorkflowHistoryRequest\x1a*.dandori.api.v1.GetWorkflowHistoryResponse\x12h\n" +
	"\x11TerminateWorkflow\x12(.dandori.api.v1.TerminateWorkflowRequest\x1a).dandori.api.v1.TerminateWorkflowResponse\x12_\n" +
	"\x0eSignalWorkflow\x12%.dandori.api.v1.SignalWorkflowRequest\x1a&.dandori.api.v1.SignalWorkflowResponse\x12_\n" +
	"\x0eCancelWorkflow\x12%.dandori.api.v1.CancelWorkflowRequest\x1a&.dandori.api.v1.CancelWorkflowResponse\x12e\n" +
	"\x10PollWorkflowTask\x12'.dandori.api.v1.PollWorkflowTaskRequest\x1a(.dandori.api.v1.PollWorkflowTaskResponse\x12q\n" +
	"\x14CompleteWorkflowTask\x12+.dandori.api.v1.CompleteWorkflowTaskRequest\x1a,.dandori.api.v1.CompleteWorkflowTaskResponse\x12e\n" +
	"\x10FailWorkflowTask\x12'.dandori.api.v1.FailWorkflowTaskRequest\x1a(.dandori.api.v1.FailWorkflowTaskResponse\x12e\n" +
	"\x10PollActivityTask\x12'.dandori.api.v1.PollActivityTaskRequest\x1a(.dandori.api.v1.PollActivityTaskResponse\x12q\n" +
	"\x14CompleteActivityTask\x12+.dandori.api.v1.CompleteActivityTaskRequest\x1a,.dandori.api.v1.CompleteActivityTaskResponse\x12e\n" +
	"\x10FailActivityTask\x12'.dandori.api.v1.FailActivityTaskRequest\x1a(.dandori.api.v1.FailActivityTaskResponse\x12z\n" +
	"\x17RecordActivityHeartbeat\x12..dandori.api.v1.RecordActivityHeartbeatRequest\x1a/.dandori.api.v1.RecordActivityHeartbeatResponseB*Z(github.com/asakaida/dandori/api/v1;apiv1b\x06proto3"

var (
	file_api_v1_service_proto_rawDescOnce sync.Once
	file_api_v1_service_proto_rawDescData []byte
)

func file_api_v1_service_proto_rawDescGZIP() []byte {
	file_api_v1_service_proto_rawDescOnce.Do(func() {
		file_api_v1_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_service_proto_rawDesc), len(file_api_v1_service_proto_rawDesc)))
	})
	return file_api_v1_service_proto_rawDescData
}

var file_api_v1_service_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_api_v1_service_proto_goTypes = []any{
	(*StartWorkflowRequest)(nil),            // 0: dandori.api.v1.StartWorkflowRequest
	(*StartWorkflowResponse)(nil),           // 1: dandori.api.v1.StartWorkflowResponse
	(*DescribeWorkflowRequest)(nil),         // 2: dandori.api.v1.DescribeWorkflowRequest
	(*DescribeWorkflowResponse)(nil),        // 3: dandori.api.v1.DescribeWorkflowResponse
	(*GetWorkflowHistoryRequest)(nil),       // 4: dandori.api.v1.GetWorkflowHistoryRequest
	(*GetWorkflowHistoryResponse)(nil),      // 5: dandori.api.v1.GetWorkflowHistoryResponse
	(*TerminateWorkflowRequest)(nil),        // 6: dandori.api.v1.TerminateWorkflowRequest
	(*TerminateWorkflowResponse)(nil),       // 7: dandori.api.v1.TerminateWorkflowResponse
	(*SignalWorkflowRequest)(nil),           // 8: dandori.api.v1.SignalWorkflowRequest
	(*SignalWorkflowResponse)(nil),          // 9: dandori.api.v1.SignalWorkflowResponse
	(*PollWorkflowTaskRequest)(nil),         // 10: dandori.api.v1.PollWorkflowTaskRequest
	(*PollWorkflowTaskResponse)(nil),        // 11: dandori.api.v1.PollWorkflowTaskResponse
	(*CompleteWorkflowTaskRequest)(nil),     // 12: dandori.api.v1.CompleteWorkflowTaskRequest
	(*CompleteWorkflowTaskResponse)(nil),    // 13: dandori.api.v1.CompleteWorkflowTaskResponse
	(*FailWorkflowTaskRequest)(nil),         // 14: dandori.api.v1.FailWorkflowTaskRequest
	(*FailWorkflowTaskResponse)(nil),        // 15: dandori.api.v1.FailWorkflowTaskResponse
	(*PollActivityTaskRequest)(nil),         // 16: dandori.api.v1.PollActivityTaskRequest
	(*PollActivityTaskResponse)(nil),        // 17: dandori.api.v1.PollActivityTaskResponse
	(*CompleteActivityTaskRequest)(nil),     // 18: dandori.api.v1.CompleteActivityTaskRequest
	(*CompleteActivityTaskResponse)(nil),    // 19: dandori.api.v1.CompleteActivityTaskResponse
	(*FailActivityTaskRequest)(nil),         // 20: dandori.api.v1.FailActivityTaskRequest
	(*FailActivityTaskResponse)(nil),        // 21: dandori.api.v1.FailActivityTaskResponse
	(*CancelWorkflowRequest)(nil),           // 22: dandori.api.v1.CancelWorkflowRequest
	(*CancelWorkflowResponse)(nil),          // 23: dandori.api.v1.CancelWorkflowResponse
	(*RecordActivityHeartbeatRequest)(nil),  // 24: dandori.api.v1.RecordActivityHeartbeatRequest
	(*RecordActivityHeartbeatResponse)(nil), // 25: dandori.api.v1.RecordActivityHeartbeatResponse
	(*WorkflowExecution)(nil),               // 26: dandori.api.v1.WorkflowExecution
	(*HistoryEvent)(nil),                    // 27: dandori.api.v1.HistoryEvent
	(*Command)(nil),                         // 28: dandori.api.v1.Command
	(*timestamppb.Timestamp)(nil),           // 29: google.protobuf.Timestamp
	(*ActivityFailure)(nil),                 // 30: dandori.api.v1.ActivityFailure
}
var file_api_v1_service_proto_depIdxs = []int32{
	26, // 0: dandori.api.v1.DescribeWorkflowResponse.workflow_execution:type_name -> dandori.api.v1.WorkflowExecution
	27, // 1: dandori.api.v1.GetWorkflowHistoryResponse.events:type_name -> dandori.api.v1.HistoryEvent
	27, // 2: dandori.api.v1.PollWorkflowTaskResponse.events:type_name -> dandori.api.v1.HistoryEvent
	28, // 3: dandori.api.v1.CompleteWorkflowTaskRequest.commands:type_name -> dandori.api.v1.Command
	29, // 4: dandori.api.v1.PollActivityTaskResponse.scheduled_at:type_name -> google.protobuf.Timestamp
	30, // 5: dandori.api.v1.FailActivityTaskRequest.failure:type_name -> dandori.api.v1.ActivityFailure
	0,  // 6: dandori.api.v1.DandoriService.StartWorkflow:input_type -> dandori.api.v1.StartWorkflowRequest
	2,  // 7: dandori.api.v1.DandoriService.DescribeWorkflow:input_type -> dandori.api.v1.DescribeWorkflowRequest
	4,  // 8: dandori.api.v1.DandoriService.GetWorkflowHistory:input_type -> dandori.api.v1.GetWorkflowHistoryRequest
	6,  // 9: dandori.api.v1.DandoriService.TerminateWorkflow:input_type -> dandori.api.v1.TerminateWorkflowRequest
	8,  // 10: dandori.api.v1.DandoriService.SignalWorkflow:input_type -> dandori.api.v1.SignalWorkflowRequest
	22, // 11: dandori.api.v1.DandoriService.CancelWorkflow:input_type -> dandori.api.v1.CancelWorkflowRequest
	10, // 12: dandori.api.v1.DandoriService.PollWorkflowTask:input_type -> dandori.api.v1.PollWorkflowTaskRequest
	12, // 13: dandori.api.v1.DandoriService.CompleteWorkflowTask:input_type -> dandori.api.v1.CompleteWorkflowTaskRequest
	14, // 14: dandori.api.v1.DandoriService.FailWorkflowTask:input_type -> dandori.api.v1.FailWorkflowTaskRequest
	16, // 15: dandori.api.v1.DandoriService.PollActivityTask:input_type -> dandori.api.v1.PollActivityTaskRequest
	18, // 16: dandori.api.v1.DandoriService.CompleteActivityTask:input_type -> dandori.api.v1.CompleteActivityTaskRequest
	20, // 17: dandori.api.v1.DandoriService.FailActivityTask:input_type -> dandori.api.v1.FailActivityTaskRequest
	24, // 18: dandori.api.v1.DandoriService.RecordActivityHeartbeat:input_type -> dandori.api.v1.RecordActivityHeartbeatRequest
	1,  // 19: dandori.api.v1.DandoriService.StartWorkflow:output_type -> dandori.api.v1.StartWorkflowResponse
	3,  // 20: dandori.api.v1.DandoriService.DescribeWorkflow:output_type -> dandori.api.v1.DescribeWorkflowResponse
	5,  // 21: dandori.api.v1.DandoriService.GetWorkflowHistory:output_type -> dandori.api.v1.GetWorkflowHistoryResponse
	7,  // 22: dandori.api.v1.DandoriService.TerminateWorkflow:output_type -> dandori.api.v1.TerminateWorkflowResponse
	9,  // 23: dandori.api.v1.DandoriService.SignalWorkflow:output_type -> dandori.api.v1.SignalWorkflowResponse
	23, // 24: dandori.api.v1.DandoriService.CancelWorkflow:output_type -> dandori.api.v1.CancelWorkflowResponse
	11, // 25: dandori.api.v1.DandoriService.PollWorkflowTask:output_type -> dandori.api.v1.PollWorkflowTaskResponse
	13, // 26: dandori.api.v1.DandoriService.CompleteWorkflowTask:output_type -> dandori.api.v1.CompleteWorkflowTaskResponse
	15, // 27: dandori.api.v1.DandoriService.FailWorkflowTask:output_type -> dandori.api.v1.FailWorkflowTaskResponse
	17, // 28: dandori.api.v1.DandoriService.PollActivityTask:output_type -> dandori.api.v1.PollActivityTaskResponse
	19, // 29: dandori.api.v1.DandoriService.CompleteActivityTask:output_type -> dandori.api.v1.CompleteActivityTaskResponse
	21, // 30: dandori.api.v1.DandoriService.FailActivityTask:output_type -> dandori.api.v1.FailActivityTaskResponse
	25, // 31: dandori.api.v1.DandoriService.RecordActivityHeartbeat:output_type -> dandori.api.v1.RecordActivityHeartbeatResponse
	19, // [19:32] is the sub-list for method output_type
	6,  // [6:19] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_v1_service_proto_init() }
func file_api_v1_service_proto_init() {
	if File_api_v1_service_proto != nil {
		return
	}
	file_api_v1_types_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_service_proto_rawDesc), len(file_api_v1_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_v1_service_proto_goTypes,
		DependencyIndexes: file_api_v1_service_proto_depIdxs,
		MessageInfos:      file_api_v1_service_proto_msgTypes,
	}.Build()
	File_api_v1_service_proto = out.File
	file_api_v1_service_proto_goTypes = nil
	file_api_v1_service_proto_depIdxs = nil
}
