// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: api/v1/service.proto

package apiv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DandoriService_StartWorkflow_FullMethodName        = "/dandori.api.v1.DandoriService/StartWorkflow"
	DandoriService_DescribeWorkflow_FullMethodName     = "/dandori.api.v1.DandoriService/DescribeWorkflow"
	DandoriService_GetWorkflowHistory_FullMethodName   = "/dandori.api.v1.DandoriService/GetWorkflowHistory"
	DandoriService_TerminateWorkflow_FullMethodName    = "/dandori.api.v1.DandoriService/TerminateWorkflow"
	DandoriService_PollWorkflowTask_FullMethodName     = "/dandori.api.v1.DandoriService/PollWorkflowTask"
	DandoriService_CompleteWorkflowTask_FullMethodName = "/dandori.api.v1.DandoriService/CompleteWorkflowTask"
	DandoriService_FailWorkflowTask_FullMethodName     = "/dandori.api.v1.DandoriService/FailWorkflowTask"
	DandoriService_PollActivityTask_FullMethodName     = "/dandori.api.v1.DandoriService/PollActivityTask"
	DandoriService_CompleteActivityTask_FullMethodName = "/dandori.api.v1.DandoriService/CompleteActivityTask"
	DandoriService_FailActivityTask_FullMethodName     = "/dandori.api.v1.DandoriService/FailActivityTask"
)

// DandoriServiceClient is the client API for DandoriService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DandoriServiceClient interface {
	// Client API
	StartWorkflow(ctx context.Context, in *StartWorkflowRequest, opts ...grpc.CallOption) (*StartWorkflowResponse, error)
	DescribeWorkflow(ctx context.Context, in *DescribeWorkflowRequest, opts ...grpc.CallOption) (*DescribeWorkflowResponse, error)
	GetWorkflowHistory(ctx context.Context, in *GetWorkflowHistoryRequest, opts ...grpc.CallOption) (*GetWorkflowHistoryResponse, error)
	TerminateWorkflow(ctx context.Context, in *TerminateWorkflowRequest, opts ...grpc.CallOption) (*TerminateWorkflowResponse, error)
	// Worker API: Workflow Task
	PollWorkflowTask(ctx context.Context, in *PollWorkflowTaskRequest, opts ...grpc.CallOption) (*PollWorkflowTaskResponse, error)
	CompleteWorkflowTask(ctx context.Context, in *CompleteWorkflowTaskRequest, opts ...grpc.CallOption) (*CompleteWorkflowTaskResponse, error)
	FailWorkflowTask(ctx context.Context, in *FailWorkflowTaskRequest, opts ...grpc.CallOption) (*FailWorkflowTaskResponse, error)
	// Worker API: Activity Task
	PollActivityTask(ctx context.Context, in *PollActivityTaskRequest, opts ...grpc.CallOption) (*PollActivityTaskResponse, error)
	CompleteActivityTask(ctx context.Context, in *CompleteActivityTaskRequest, opts ...grpc.CallOption) (*CompleteActivityTaskResponse, error)
	FailActivityTask(ctx context.Context, in *FailActivityTaskRequest, opts ...grpc.CallOption) (*FailActivityTaskResponse, error)
}

type dandoriServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDandoriServiceClient(cc grpc.ClientConnInterface) DandoriServiceClient {
	return &dandoriServiceClient{cc}
}

func (c *dandoriServiceClient) StartWorkflow(ctx context.Context, in *StartWorkflowRequest, opts ...grpc.CallOption) (*StartWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartWorkflowResponse)
	err := c.cc.Invoke(ctx, DandoriService_StartWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dandoriServiceClient) DescribeWorkflow(ctx context.Context, in *DescribeWorkflowRequest, opts ...grpc.CallOption) (*DescribeWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeWorkflowResponse)
	err := c.cc.Invoke(ctx, DandoriService_DescribeWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dandoriServiceClient) GetWorkflowHistory(ctx context.Context, in *GetWorkflowHistoryRequest, opts ...grpc.CallOption) (*GetWorkflowHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWorkflowHistoryResponse)
	err := c.cc.Invoke(ctx, DandoriService_GetWorkflowHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dandoriServiceClient) TerminateWorkflow(ctx context.Context, in *TerminateWorkflowRequest, opts ...grpc.CallOption) (*TerminateWorkflowResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TerminateWorkflowResponse)
	err := c.cc.Invoke(ctx, DandoriService_TerminateWorkflow_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dandoriServiceClient) PollWorkflowTask(ctx context.Context, in *PollWorkflowTaskRequest, opts ...grpc.CallOption) (*PollWorkflowTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PollWorkflowTaskResponse)
	err := c.cc.Invoke(ctx, DandoriService_PollWorkflowTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dandoriServiceClient) CompleteWorkflowTask(ctx context.Context, in *CompleteWorkflowTaskRequest, opts ...grpc.CallOption) (*CompleteWorkflowTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteWorkflowTaskResponse)
	err := c.cc.Invoke(ctx, DandoriService_CompleteWorkflowTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dandoriServiceClient) FailWorkflowTask(ctx context.Context, in *FailWorkflowTaskRequest, opts ...grpc.CallOption) (*FailWorkflowTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FailWorkflowTaskResponse)
	err := c.cc.Invoke(ctx, DandoriService_FailWorkflowTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dandoriServiceClient) PollActivityTask(ctx context.Context, in *PollActivityTaskRequest, opts ...grpc.CallOption) (*PollActivityTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PollActivityTaskResponse)
	err := c.cc.Invoke(ctx, DandoriService_PollActivityTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dandoriServiceClient) CompleteActivityTask(ctx context.Context, in *CompleteActivityTaskRequest, opts ...grpc.CallOption) (*CompleteActivityTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteActivityTaskResponse)
	err := c.cc.Invoke(ctx, DandoriService_CompleteActivityTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dandoriServiceClient) FailActivityTask(ctx context.Context, in *FailActivityTaskRequest, opts ...grpc.CallOption) (*FailActivityTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FailActivityTaskResponse)
	err := c.cc.Invoke(ctx, DandoriService_FailActivityTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DandoriServiceServer is the server API for DandoriService service.
// All implementations must embed UnimplementedDandoriServiceServer
// for forward compatibility.
type DandoriServiceServer interface {
	// Client API
	StartWorkflow(context.Context, *StartWorkflowRequest) (*StartWorkflowResponse, error)
	DescribeWorkflow(context.Context, *DescribeWorkflowRequest) (*DescribeWorkflowResponse, error)
	GetWorkflowHistory(context.Context, *GetWorkflowHistoryRequest) (*GetWorkflowHistoryResponse, error)
	TerminateWorkflow(context.Context, *TerminateWorkflowRequest) (*TerminateWorkflowResponse, error)
	// Worker API: Workflow Task
	PollWorkflowTask(context.Context, *PollWorkflowTaskRequest) (*PollWorkflowTaskResponse, error)
	CompleteWorkflowTask(context.Context, *CompleteWorkflowTaskRequest) (*CompleteWorkflowTaskResponse, error)
	FailWorkflowTask(context.Context, *FailWorkflowTaskRequest) (*FailWorkflowTaskResponse, error)
	// Worker API: Activity Task
	PollActivityTask(context.Context, *PollActivityTaskRequest) (*PollActivityTaskResponse, error)
	CompleteActivityTask(context.Context, *CompleteActivityTaskRequest) (*CompleteActivityTaskResponse, error)
	FailActivityTask(context.Context, *FailActivityTaskRequest) (*FailActivityTaskResponse, error)
	mustEmbedUnimplementedDandoriServiceServer()
}

// UnimplementedDandoriServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDandoriServiceServer struct{}

func (UnimplementedDandoriServiceServer) StartWorkflow(context.Context, *StartWorkflowRequest) (*StartWorkflowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartWorkflow not implemented")
}
func (UnimplementedDandoriServiceServer) DescribeWorkflow(context.Context, *DescribeWorkflowRequest) (*DescribeWorkflowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DescribeWorkflow not implemented")
}
func (UnimplementedDandoriServiceServer) GetWorkflowHistory(context.Context, *GetWorkflowHistoryRequest) (*GetWorkflowHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWorkflowHistory not implemented")
}
func (UnimplementedDandoriServiceServer) TerminateWorkflow(context.Context, *TerminateWorkflowRequest) (*TerminateWorkflowResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method TerminateWorkflow not implemented")
}
func (UnimplementedDandoriServiceServer) PollWorkflowTask(context.Context, *PollWorkflowTaskRequest) (*PollWorkflowTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PollWorkflowTask not implemented")
}
func (UnimplementedDandoriServiceServer) CompleteWorkflowTask(context.Context, *CompleteWorkflowTaskRequest) (*CompleteWorkflowTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteWorkflowTask not implemented")
}
func (UnimplementedDandoriServiceServer) FailWorkflowTask(context.Context, *FailWorkflowTaskRequest) (*FailWorkflowTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FailWorkflowTask not implemented")
}
func (UnimplementedDandoriServiceServer) PollActivityTask(context.Context, *PollActivityTaskRequest) (*PollActivityTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PollActivityTask not implemented")
}
func (UnimplementedDandoriServiceServer) CompleteActivityTask(context.Context, *CompleteActivityTaskRequest) (*CompleteActivityTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteActivityTask not implemented")
}
func (UnimplementedDandoriServiceServer) FailActivityTask(context.Context, *FailActivityTaskRequest) (*FailActivityTaskResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FailActivityTask not implemented")
}
func (UnimplementedDandoriServiceServer) mustEmbedUnimplementedDandoriServiceServer() {}
func (UnimplementedDandoriServiceServer) testEmbeddedByValue()                        {}

// UnsafeDandoriServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DandoriServiceServer will
// result in compilation errors.
type UnsafeDandoriServiceServer interface {
	mustEmbedUnimplementedDandoriServiceServer()
}

func RegisterDandoriServiceServer(s grpc.ServiceRegistrar, srv DandoriServiceServer) {
	// If the following call panics, it indicates UnimplementedDandoriServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DandoriService_ServiceDesc, srv)
}

func _DandoriService_StartWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DandoriServiceServer).StartWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DandoriService_StartWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DandoriServiceServer).StartWorkflow(ctx, req.(*StartWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DandoriService_DescribeWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DandoriServiceServer).DescribeWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DandoriService_DescribeWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DandoriServiceServer).DescribeWorkflow(ctx, req.(*DescribeWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DandoriService_GetWorkflowHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWorkflowHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DandoriServiceServer).GetWorkflowHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DandoriService_GetWorkflowHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DandoriServiceServer).GetWorkflowHistory(ctx, req.(*GetWorkflowHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DandoriService_TerminateWorkflow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateWorkflowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DandoriServiceServer).TerminateWorkflow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DandoriService_TerminateWorkflow_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DandoriServiceServer).TerminateWorkflow(ctx, req.(*TerminateWorkflowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DandoriService_PollWorkflowTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollWorkflowTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DandoriServiceServer).PollWorkflowTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DandoriService_PollWorkflowTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DandoriServiceServer).PollWorkflowTask(ctx, req.(*PollWorkflowTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DandoriService_CompleteWorkflowTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteWorkflowTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DandoriServiceServer).CompleteWorkflowTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DandoriService_CompleteWorkflowTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DandoriServiceServer).CompleteWorkflowTask(ctx, req.(*CompleteWorkflowTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DandoriService_FailWorkflowTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailWorkflowTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DandoriServiceServer).FailWorkflowTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DandoriService_FailWorkflowTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DandoriServiceServer).FailWorkflowTask(ctx, req.(*FailWorkflowTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DandoriService_PollActivityTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PollActivityTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DandoriServiceServer).PollActivityTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DandoriService_PollActivityTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DandoriServiceServer).PollActivityTask(ctx, req.(*PollActivityTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DandoriService_CompleteActivityTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteActivityTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DandoriServiceServer).CompleteActivityTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DandoriService_CompleteActivityTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DandoriServiceServer).CompleteActivityTask(ctx, req.(*CompleteActivityTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DandoriService_FailActivityTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FailActivityTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DandoriServiceServer).FailActivityTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DandoriService_FailActivityTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DandoriServiceServer).FailActivityTask(ctx, req.(*FailActivityTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DandoriService_ServiceDesc is the grpc.ServiceDesc for DandoriService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DandoriService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "dandori.api.v1.DandoriService",
	HandlerType: (*DandoriServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartWorkflow",
			Handler:    _DandoriService_StartWorkflow_Handler,
		},
		{
			MethodName: "DescribeWorkflow",
			Handler:    _DandoriService_DescribeWorkflow_Handler,
		},
		{
			MethodName: "GetWorkflowHistory",
			Handler:    _DandoriService_GetWorkflowHistory_Handler,
		},
		{
			MethodName: "TerminateWorkflow",
			Handler:    _DandoriService_TerminateWorkflow_Handler,
		},
		{
			MethodName: "PollWorkflowTask",
			Handler:    _DandoriService_PollWorkflowTask_Handler,
		},
		{
			MethodName: "CompleteWorkflowTask",
			Handler:    _DandoriService_CompleteWorkflowTask_Handler,
		},
		{
			MethodName: "FailWorkflowTask",
			Handler:    _DandoriService_FailWorkflowTask_Handler,
		},
		{
			MethodName: "PollActivityTask",
			Handler:    _DandoriService_PollActivityTask_Handler,
		},
		{
			MethodName: "CompleteActivityTask",
			Handler:    _DandoriService_CompleteActivityTask_Handler,
		},
		{
			MethodName: "FailActivityTask",
			Handler:    _DandoriService_FailActivityTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/service.proto",
}
