// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v7.34.0
// source: api/v1/types.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WorkflowExecutionStatus int32

const (
	WorkflowExecutionStatus_WORKFLOW_EXECUTION_STATUS_UNSPECIFIED      WorkflowExecutionStatus = 0
	WorkflowExecutionStatus_WORKFLOW_EXECUTION_STATUS_RUNNING          WorkflowExecutionStatus = 1
	WorkflowExecutionStatus_WORKFLOW_EXECUTION_STATUS_COMPLETED        WorkflowExecutionStatus = 2
	WorkflowExecutionStatus_WORKFLOW_EXECUTION_STATUS_FAILED           WorkflowExecutionStatus = 3
	WorkflowExecutionStatus_WORKFLOW_EXECUTION_STATUS_TERMINATED       WorkflowExecutionStatus = 4
	WorkflowExecutionStatus_WORKFLOW_EXECUTION_STATUS_CONTINUED_AS_NEW WorkflowExecutionStatus = 5
)

// Enum value maps for WorkflowExecutionStatus.
var (
	WorkflowExecutionStatus_name = map[int32]string{
		0: "WORKFLOW_EXECUTION_STATUS_UNSPECIFIED",
		1: "WORKFLOW_EXECUTION_STATUS_RUNNING",
		2: "WORKFLOW_EXECUTION_STATUS_COMPLETED",
		3: "WORKFLOW_EXECUTION_STATUS_FAILED",
		4: "WORKFLOW_EXECUTION_STATUS_TERMINATED",
		5: "WORKFLOW_EXECUTION_STATUS_CONTINUED_AS_NEW",
	}
	WorkflowExecutionStatus_value = map[string]int32{
		"WORKFLOW_EXECUTION_STATUS_UNSPECIFIED":      0,
		"WORKFLOW_EXECUTION_STATUS_RUNNING":          1,
		"WORKFLOW_EXECUTION_STATUS_COMPLETED":        2,
		"WORKFLOW_EXECUTION_STATUS_FAILED":           3,
		"WORKFLOW_EXECUTION_STATUS_TERMINATED":       4,
		"WORKFLOW_EXECUTION_STATUS_CONTINUED_AS_NEW": 5,
	}
)

func (x WorkflowExecutionStatus) Enum() *WorkflowExecutionStatus {
	p := new(WorkflowExecutionStatus)
	*p = x
	return p
}

func (x WorkflowExecutionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkflowExecutionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_types_proto_enumTypes[0].Descriptor()
}

func (WorkflowExecutionStatus) Type() protoreflect.EnumType {
	return &file_api_v1_types_proto_enumTypes[0]
}

func (x WorkflowExecutionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkflowExecutionStatus.Descriptor instead.
func (WorkflowExecutionStatus) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_types_proto_rawDescGZIP(), []int{0}
}

type CommandType int32

const (
	CommandType_COMMAND_TYPE_UNSPECIFIED              CommandType = 0
	CommandType_COMMAND_TYPE_SCHEDULE_ACTIVITY_TASK   CommandType = 1
	CommandType_COMMAND_TYPE_COMPLETE_WORKFLOW        CommandType = 2
	CommandType_COMMAND_TYPE_FAIL_WORKFLOW            CommandType = 3
	CommandType_COMMAND_TYPE_START_TIMER              CommandType = 4
	CommandType_COMMAND_TYPE_CANCEL_TIMER             CommandType = 5
	CommandType_COMMAND_TYPE_RECORD_SIDE_EFFECT       CommandType = 6
	CommandType_COMMAND_TYPE_START_CHILD_WORKFLOW     CommandType = 7
	CommandType_COMMAND_TYPE_CONTINUE_AS_NEW          CommandType = 9
	CommandType_COMMAND_TYPE_UPSERT_SEARCH_ATTRIBUTES CommandType = 10
)

// Enum value maps for CommandType.
var (
	CommandType_name = map[int32]string{
		0:  "COMMAND_TYPE_UNSPECIFIED",
		1:  "COMMAND_TYPE_SCHEDULE_ACTIVITY_TASK",
		2:  "COMMAND_TYPE_COMPLETE_WORKFLOW",
		3:  "COMMAND_TYPE_FAIL_WORKFLOW",
		4:  "COMMAND_TYPE_START_TIMER",
		5:  "COMMAND_TYPE_CANCEL_TIMER",
		6:  "COMMAND_TYPE_RECORD_SIDE_EFFECT",
		7:  "COMMAND_TYPE_START_CHILD_WORKFLOW",
		9:  "COMMAND_TYPE_CONTINUE_AS_NEW",
		10: "COMMAND_TYPE_UPSERT_SEARCH_ATTRIBUTES",
	}
	CommandType_value = map[string]int32{
		"COMMAND_TYPE_UNSPECIFIED":              0,
		"COMMAND_TYPE_SCHEDULE_ACTIVITY_TASK":   1,
		"COMMAND_TYPE_COMPLETE_WORKFLOW":        2,
		"COMMAND_TYPE_FAIL_WORKFLOW":            3,
		"COMMAND_TYPE_START_TIMER":              4,
		"COMMAND_TYPE_CANCEL_TIMER":             5,
		"COMMAND_TYPE_RECORD_SIDE_EFFECT":       6,
		"COMMAND_TYPE_START_CHILD_WORKFLOW":     7,
		"COMMAND_TYPE_CONTINUE_AS_NEW":          9,
		"COMMAND_TYPE_UPSERT_SEARCH_ATTRIBUTES": 10,
	}
)

func (x CommandType) Enum() *CommandType {
	p := new(CommandType)
	*p = x
	return p
}

func (x CommandType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommandType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_v1_types_proto_enumTypes[1].Descriptor()
}

func (CommandType) Type() protoreflect.EnumType {
	return &file_api_v1_types_proto_enumTypes[1]
}

func (x CommandType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommandType.Descriptor instead.
func (CommandType) EnumDescriptor() ([]byte, []int) {
	return file_api_v1_types_proto_rawDescGZIP(), []int{1}
}

type WorkflowExecution struct {
	state            protoimpl.MessageState  `protogen:"open.v1"`
	Id               string                  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkflowType     string                  `protobuf:"bytes,2,opt,name=workflow_type,json=workflowType,proto3" json:"workflow_type,omitempty"`
	TaskQueue        string                  `protobuf:"bytes,3,opt,name=task_queue,json=taskQueue,proto3" json:"task_queue,omitempty"`
	Status           WorkflowExecutionStatus `protobuf:"varint,4,opt,name=status,proto3,enum=dandori.api.v1.WorkflowExecutionStatus" json:"status,omitempty"`
	Input            []byte                  `protobuf:"bytes,5,opt,name=input,proto3" json:"input,omitempty"`
	Result           []byte                  `protobuf:"bytes,6,opt,name=result,proto3" json:"result,omitempty"`
	ErrorMessage     string                  `protobuf:"bytes,7,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	CreatedAt        *timestamppb.Timestamp  `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp  `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	ClosedAt         *timestamppb.Timestamp  `protobuf:"bytes,10,opt,name=closed_at,json=closedAt,proto3" json:"closed_at,omitempty"`
	ParentWorkflowId string                  `protobuf:"bytes,11,opt,name=parent_workflow_id,json=parentWorkflowId,proto3" json:"parent_workflow_id,omitempty"`
	ParentSeqId      int64                   `protobuf:"varint,12,opt,name=parent_seq_id,json=parentSeqId,proto3" json:"parent_seq_id,omitempty"`
	CronSchedule     string                  `protobuf:"bytes,13,opt,name=cron_schedule,json=cronSchedule,proto3" json:"cron_schedule,omitempty"`
	ContinuedAsNewId string                  `protobuf:"bytes,14,opt,name=continued_as_new_id,json=continuedAsNewId,proto3" json:"continued_as_new_id,omitempty"`
	Namespace        string                  `protobuf:"bytes,15,opt,name=namespace,proto3" json:"namespace,omitempty"`
	SearchAttributes map[string]string       `protobuf:"bytes,16,rep,name=search_attributes,json=searchAttributes,proto3" json:"search_attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *WorkflowExecution) Reset() {
	*x = WorkflowExecution{}
	mi := &file_api_v1_types_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowExecution) ProtoMessage() {}

func (x *WorkflowExecution) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_types_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowExecution.ProtoReflect.Descriptor instead.
func (*WorkflowExecution) Descriptor() ([]byte, []int) {
	return file_api_v1_types_proto_rawDescGZIP(), []int{0}
}

func (x *WorkflowExecution) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WorkflowExecution) GetWorkflowType() string {
	if x != nil {
		return x.WorkflowType
	}
	return ""
}

func (x *WorkflowExecution) GetTaskQueue() string {
	if x != nil {
		return x.TaskQueue
	}
	return ""
}

func (x *WorkflowExecution) GetStatus() WorkflowExecutionStatus {
	if x != nil {
		return x.Status
	}
	return WorkflowExecutionStatus_WORKFLOW_EXECUTION_STATUS_UNSPECIFIED
}

func (x *WorkflowExecution) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *WorkflowExecution) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *WorkflowExecution) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *WorkflowExecution) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *WorkflowExecution) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *WorkflowExecution) GetClosedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ClosedAt
	}
	return nil
}

func (x *WorkflowExecution) GetParentWorkflowId() string {
	if x != nil {
		return x.ParentWorkflowId
	}
	return ""
}

func (x *WorkflowExecution) GetParentSeqId() int64 {
	if x != nil {
		return x.ParentSeqId
	}
	return 0
}

func (x *WorkflowExecution) GetCronSchedule() string {
	if x != nil {
		return x.CronSchedule
	}
	return ""
}

func (x *WorkflowExecution) GetContinuedAsNewId() string {
	if x != nil {
		return x.ContinuedAsNewId
	}
	return ""
}

func (x *WorkflowExecution) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *WorkflowExecution) GetSearchAttributes() map[string]string {
	if x != nil {
		return x.SearchAttributes
	}
	return nil
}

type HistoryEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	SequenceNum   int32                  `protobuf:"varint,3,opt,name=sequence_num,json=sequenceNum,proto3" json:"sequence_num,omitempty"`
	EventType     string                 `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	EventData     []byte                 `protobuf:"bytes,5,opt,name=event_data,json=eventData,proto3" json:"event_data,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HistoryEvent) Reset() {
	*x = HistoryEvent{}
	mi := &file_api_v1_types_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HistoryEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HistoryEvent) ProtoMessage() {}

func (x *HistoryEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_types_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HistoryEvent.ProtoReflect.Descriptor instead.
func (*HistoryEvent) Descriptor() ([]byte, []int) {
	return file_api_v1_types_proto_rawDescGZIP(), []int{1}
}

func (x *HistoryEvent) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *HistoryEvent) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *HistoryEvent) GetSequenceNum() int32 {
	if x != nil {
		return x.SequenceNum
	}
	return 0
}

func (x *HistoryEvent) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *HistoryEvent) GetEventData() []byte {
	if x != nil {
		return x.EventData
	}
	return nil
}

func (x *HistoryEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          CommandType            `protobuf:"varint,1,opt,name=type,proto3,enum=dandori.api.v1.CommandType" json:"type,omitempty"`
	Attributes    []byte                 `protobuf:"bytes,2,opt,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_api_v1_types_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_types_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_api_v1_types_proto_rawDescGZIP(), []int{2}
}

func (x *Command) GetType() CommandType {
	if x != nil {
		return x.Type
	}
	return CommandType_COMMAND_TYPE_UNSPECIFIED
}

func (x *Command) GetAttributes() []byte {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type ScheduleActivityTaskAttributes struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	SeqId                  int64                  `protobuf:"varint,1,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`
	ActivityType           string                 `protobuf:"bytes,2,opt,name=activity_type,json=activityType,proto3" json:"activity_type,omitempty"`
	Input                  []byte                 `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	TaskQueue              string                 `protobuf:"bytes,4,opt,name=task_queue,json=taskQueue,proto3" json:"task_queue,omitempty"`
	StartToCloseTimeout    *durationpb.Duration   `protobuf:"bytes,5,opt,name=start_to_close_timeout,json=startToCloseTimeout,proto3" json:"start_to_close_timeout,omitempty"`
	RetryPolicy            *RetryPolicy           `protobuf:"bytes,6,opt,name=retry_policy,json=retryPolicy,proto3" json:"retry_policy,omitempty"`
	HeartbeatTimeout       *durationpb.Duration   `protobuf:"bytes,7,opt,name=heartbeat_timeout,json=heartbeatTimeout,proto3" json:"heartbeat_timeout,omitempty"`
	ScheduleToCloseTimeout int64                  `protobuf:"varint,8,opt,name=schedule_to_close_timeout,json=scheduleToCloseTimeout,proto3" json:"schedule_to_close_timeout,omitempty"`
	ScheduleToStartTimeout int64                  `protobuf:"varint,9,opt,name=schedule_to_start_timeout,json=scheduleToStartTimeout,proto3" json:"schedule_to_start_timeout,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ScheduleActivityTaskAttributes) Reset() {
	*x = ScheduleActivityTaskAttributes{}
	mi := &file_api_v1_types_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleActivityTaskAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleActivityTaskAttributes) ProtoMessage() {}

func (x *ScheduleActivityTaskAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_types_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleActivityTaskAttributes.ProtoReflect.Descriptor instead.
func (*ScheduleActivityTaskAttributes) Descriptor() ([]byte, []int) {
	return file_api_v1_types_proto_rawDescGZIP(), []int{3}
}

func (x *ScheduleActivityTaskAttributes) GetSeqId() int64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

func (x *ScheduleActivityTaskAttributes) GetActivityType() string {
	if x != nil {
		return x.ActivityType
	}
	return ""
}

func (x *ScheduleActivityTaskAttributes) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *ScheduleActivityTaskAttributes) GetTaskQueue() string {
	if x != nil {
		return x.TaskQueue
	}
	return ""
}

func (x *ScheduleActivityTaskAttributes) GetStartToCloseTimeout() *durationpb.Duration {
	if x != nil {
		return x.StartToCloseTimeout
	}
	return nil
}

func (x *ScheduleActivityTaskAttributes) GetRetryPolicy() *RetryPolicy {
	if x != nil {
		return x.RetryPolicy
	}
	return nil
}

func (x *ScheduleActivityTaskAttributes) GetHeartbeatTimeout() *durationpb.Duration {
	if x != nil {
		return x.HeartbeatTimeout
	}
	return nil
}

func (x *ScheduleActivityTaskAttributes) GetScheduleToCloseTimeout() int64 {
	if x != nil {
		return x.ScheduleToCloseTimeout
	}
	return 0
}

func (x *ScheduleActivityTaskAttributes) GetScheduleToStartTimeout() int64 {
	if x != nil {
		return x.ScheduleToStartTimeout
	}
	return 0
}

type CompleteWorkflowAttributes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Result        []byte                 `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteWorkflowAttributes) Reset() {
	*x = CompleteWorkflowAttributes{}
	mi := &file_api_v1_types_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteWorkflowAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteWorkflowAttributes) ProtoMessage() {}

func (x *CompleteWorkflowAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_types_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteWorkflowAttributes.ProtoReflect.Descriptor instead.
func (*CompleteWorkflowAttributes) Descriptor() ([]byte, []int) {
	return file_api_v1_types_proto_rawDescGZIP(), []int{4}
}

func (x *CompleteWorkflowAttributes) GetResult() []byte {
	if x != nil {
		return x.Result
	}
	return nil
}

type FailWorkflowAttributes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ErrorMessage  string                 `protobuf:"bytes,1,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FailWorkflowAttributes) Reset() {
	*x = FailWorkflowAttributes{}
	mi := &file_api_v1_types_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FailWorkflowAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FailWorkflowAttributes) ProtoMessage() {}

func (x *FailWorkflowAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_types_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FailWorkflowAttributes.ProtoReflect.Descriptor instead.
func (*FailWorkflowAttributes) Descriptor() ([]byte, []int) {
	return file_api_v1_types_proto_rawDescGZIP(), []int{5}
}

func (x *FailWorkflowAttributes) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

type RetryPolicy struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	MaxAttempts        int32                  `protobuf:"varint,1,opt,name=max_attempts,json=maxAttempts,proto3" json:"max_attempts,omitempty"`
	InitialInterval    *durationpb.Duration   `protobuf:"bytes,2,opt,name=initial_interval,json=initialInterval,proto3" json:"initial_interval,omitempty"`
	BackoffCoefficient float64                `protobuf:"fixed64,3,opt,name=backoff_coefficient,json=backoffCoefficient,proto3" json:"backoff_coefficient,omitempty"`
	MaxInterval        *durationpb.Duration   `protobuf:"bytes,4,opt,name=max_interval,json=maxInterval,proto3" json:"max_interval,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RetryPolicy) Reset() {
	*x = RetryPolicy{}
	mi := &file_api_v1_types_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RetryPolicy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RetryPolicy) ProtoMessage() {}

func (x *RetryPolicy) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_types_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RetryPolicy.ProtoReflect.Descriptor instead.
func (*RetryPolicy) Descriptor() ([]byte, []int) {
	return file_api_v1_types_proto_rawDescGZIP(), []int{6}
}

func (x *RetryPolicy) GetMaxAttempts() int32 {
	if x != nil {
		return x.MaxAttempts
	}
	return 0
}

func (x *RetryPolicy) GetInitialInterval() *durationpb.Duration {
	if x != nil {
		return x.InitialInterval
	}
	return nil
}

func (x *RetryPolicy) GetBackoffCoefficient() float64 {
	if x != nil {
		return x.BackoffCoefficient
	}
	return 0
}

func (x *RetryPolicy) GetMaxInterval() *durationpb.Duration {
	if x != nil {
		return x.MaxInterval
	}
	return nil
}

type StartTimerAttributes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeqId         int64                  `protobuf:"varint,1,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`
	Duration      *durationpb.Duration   `protobuf:"bytes,2,opt,name=duration,proto3" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTimerAttributes) Reset() {
	*x = StartTimerAttributes{}
	mi := &file_api_v1_types_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTimerAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTimerAttributes) ProtoMessage() {}

func (x *StartTimerAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_types_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTimerAttributes.ProtoReflect.Descriptor instead.
func (*StartTimerAttributes) Descriptor() ([]byte, []int) {
	return file_api_v1_types_proto_rawDescGZIP(), []int{7}
}

func (x *StartTimerAttributes) GetSeqId() int64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

func (x *StartTimerAttributes) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.Duration
	}
	return nil
}

type CancelTimerAttributes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeqId         int64                  `protobuf:"varint,1,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelTimerAttributes) Reset() {
	*x = CancelTimerAttributes{}
	mi := &file_api_v1_types_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelTimerAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelTimerAttributes) ProtoMessage() {}

func (x *CancelTimerAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_types_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelTimerAttributes.ProtoReflect.Descriptor instead.
func (*CancelTimerAttributes) Descriptor() ([]byte, []int) {
	return file_api_v1_types_proto_rawDescGZIP(), []int{8}
}

func (x *CancelTimerAttributes) GetSeqId() int64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

type ActivityFailure struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	NonRetryable  bool                   `protobuf:"varint,3,opt,name=non_retryable,json=nonRetryable,proto3" json:"non_retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityFailure) Reset() {
	*x = ActivityFailure{}
	mi := &file_api_v1_types_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityFailure) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityFailure) ProtoMessage() {}

func (x *ActivityFailure) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_types_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityFailure.ProtoReflect.Descriptor instead.
func (*ActivityFailure) Descriptor() ([]byte, []int) {
	return file_api_v1_types_proto_rawDescGZIP(), []int{9}
}

func (x *ActivityFailure) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ActivityFailure) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ActivityFailure) GetNonRetryable() bool {
	if x != nil {
		return x.NonRetryable
	}
	return false
}

type StartChildWorkflowAttributes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeqId         int64                  `protobuf:"varint,1,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`
	WorkflowId    string                 `protobuf:"bytes,2,opt,name=workflow_id,json=workflowId,proto3" json:"workflow_id,omitempty"`
	WorkflowType  string                 `protobuf:"bytes,3,opt,name=workflow_type,json=workflowType,proto3" json:"workflow_type,omitempty"`
	TaskQueue     string                 `protobuf:"bytes,4,opt,name=task_queue,json=taskQueue,proto3" json:"task_queue,omitempty"`
	Input         []byte                 `protobuf:"bytes,5,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartChildWorkflowAttributes) Reset() {
	*x = StartChildWorkflowAttributes{}
	mi := &file_api_v1_types_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartChildWorkflowAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartChildWorkflowAttributes) ProtoMessage() {}

func (x *StartChildWorkflowAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_types_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartChildWorkflowAttributes.ProtoReflect.Descriptor instead.
func (*StartChildWorkflowAttributes) Descriptor() ([]byte, []int) {
	return file_api_v1_types_proto_rawDescGZIP(), []int{10}
}

func (x *StartChildWorkflowAttributes) GetSeqId() int64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

func (x *StartChildWorkflowAttributes) GetWorkflowId() string {
	if x != nil {
		return x.WorkflowId
	}
	return ""
}

func (x *StartChildWorkflowAttributes) GetWorkflowType() string {
	if x != nil {
		return x.WorkflowType
	}
	return ""
}

func (x *StartChildWorkflowAttributes) GetTaskQueue() string {
	if x != nil {
		return x.TaskQueue
	}
	return ""
}

func (x *StartChildWorkflowAttributes) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

type RecordSideEffectAttributes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SeqId         int64                  `protobuf:"varint,1,opt,name=seq_id,json=seqId,proto3" json:"seq_id,omitempty"`
	Value         []byte                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordSideEffectAttributes) Reset() {
	*x = RecordSideEffectAttributes{}
	mi := &file_api_v1_types_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordSideEffectAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordSideEffectAttributes) ProtoMessage() {}

func (x *RecordSideEffectAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_types_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordSideEffectAttributes.ProtoReflect.Descriptor instead.
func (*RecordSideEffectAttributes) Descriptor() ([]byte, []int) {
	return file_api_v1_types_proto_rawDescGZIP(), []int{11}
}

func (x *RecordSideEffectAttributes) GetSeqId() int64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

func (x *RecordSideEffectAttributes) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

type ContinueAsNewAttributes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkflowType  string                 `protobuf:"bytes,1,opt,name=workflow_type,json=workflowType,proto3" json:"workflow_type,omitempty"`
	TaskQueue     string                 `protobuf:"bytes,2,opt,name=task_queue,json=taskQueue,proto3" json:"task_queue,omitempty"`
	Input         []byte                 `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ContinueAsNewAttributes) Reset() {
	*x = ContinueAsNewAttributes{}
	mi := &file_api_v1_types_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ContinueAsNewAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContinueAsNewAttributes) ProtoMessage() {}

func (x *ContinueAsNewAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_types_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContinueAsNewAttributes.ProtoReflect.Descriptor instead.
func (*ContinueAsNewAttributes) Descriptor() ([]byte, []int) {
	return file_api_v1_types_proto_rawDescGZIP(), []int{12}
}

func (x *ContinueAsNewAttributes) GetWorkflowType() string {
	if x != nil {
		return x.WorkflowType
	}
	return ""
}

func (x *ContinueAsNewAttributes) GetTaskQueue() string {
	if x != nil {
		return x.TaskQueue
	}
	return ""
}

func (x *ContinueAsNewAttributes) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

type PendingQuery struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	QueryId       int64                  `protobuf:"varint,1,opt,name=query_id,json=queryId,proto3" json:"query_id,omitempty"`
	QueryType     string                 `protobuf:"bytes,2,opt,name=query_type,json=queryType,proto3" json:"query_type,omitempty"`
	Input         []byte                 `protobuf:"bytes,3,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PendingQuery) Reset() {
	*x = PendingQuery{}
	mi := &file_api_v1_types_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PendingQuery) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PendingQuery) ProtoMessage() {}

func (x *PendingQuery) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_types_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PendingQuery.ProtoReflect.Descriptor instead.
func (*PendingQuery) Descriptor() ([]byte, []int) {
	return file_api_v1_types_proto_rawDescGZIP(), []int{13}
}

func (x *PendingQuery) GetQueryId() int64 {
	if x != nil {
		return x.QueryId
	}
	return 0
}

func (x *PendingQuery) GetQueryType() string {
	if x != nil {
		return x.QueryType
	}
	return ""
}

func (x *PendingQuery) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

type WorkflowSignaledAttributes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SignalName    string                 `protobuf:"bytes,1,opt,name=signal_name,json=signalName,proto3" json:"signal_name,omitempty"`
	Input         []byte                 `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowSignaledAttributes) Reset() {
	*x = WorkflowSignaledAttributes{}
	mi := &file_api_v1_types_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowSignaledAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowSignaledAttributes) ProtoMessage() {}

func (x *WorkflowSignaledAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_api_v1_types_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowSignaledAttributes.ProtoReflect.Descriptor instead.
func (*WorkflowSignaledAttributes) Descriptor() ([]byte, []int) {
	return file_api_v1_types_proto_rawDescGZIP(), []int{14}
}

func (x *WorkflowSignaledAttributes) GetSignalName() string {
	if x != nil {
		return x.SignalName
	}
	return ""
}

func (x *WorkflowSignaledAttributes) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

var File_api_v1_types_proto protoreflect.FileDescriptor

const file_api_v1_types_proto_rawDesc = "" +
	"\n" +
	"\x12api/v1/types.proto\x12\x0edandori.api.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"\x99\x06\n" +
	"\x11WorkflowExecution\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rworkflow_type\x18\x02 \x01(\tR\fworkflowType\x12\x1d\n" +
	"\n" +
	"task_queue\x18\x03 \x01(\tR\ttaskQueue\x12?\n" +
	"\x06status\x18\x04 \x01(\x0e2'.dandori.api.v1.WorkflowExecutionStatusR\x06status\x12\x14\n" +
	"\x05input\x18\x05 \x01(\fR\x05input\x12\x16\n" +
	"\x06result\x18\x06 \x01(\fR\x06result\x12#\n" +
	"\rerror_message\x18\a \x01(\tR\ferrorMessage\x129\n" +
	"\n" +
	"created_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x127\n" +
	"\tclosed_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\bclosedAt\x12,\n" +
	"\x12parent_workflow_id\x18\v \x01(\tR\x10parentWorkflowId\x12\"\n" +
	"\rparent_seq_id\x18\f \x01(\x03R\vparentSeqId\x12#\n" +
	"\rcron_schedule\x18\r \x01(\tR\fcronSchedule\x12-\n" +
	"\x13continued_as_new_id\x18\x0e \x01(\tR\x10continuedAsNewId\x12\x1c\n" +
	"\tnamespace\x18\x0f \x01(\tR\tnamespace\x12d\n" +
	"\x11search_attributes\x18\x10 \x03(\v27.dandori.api.v1.WorkflowExecution.SearchAttributesEntryR\x10searchAttributes\x1aC\n" +
	"\x15SearchAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xda\x01\n" +
	"\fHistoryEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12!\n" +
	"\fsequence_num\x18\x03 \x01(\x05R\vsequenceNum\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tR\teventType\x12\x1d\n" +
	"\n" +
	"event_data\x18\x05 \x01(\fR\teventData\x128\n" +
	"\ttimestamp\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\"Z\n" +
	"\aCommand\x12/\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1b.dandori.api.v1.CommandTypeR\x04type\x12\x1e\n" +
	"\n" +
	"attributes\x18\x02 \x01(\fR\n" +
	"attributes\"\xdf\x03\n" +
	"\x1eScheduleActivityTaskAttributes\x12\x15\n" +
	"\x06seq_id\x18\x01 \x01(\x03R\x05seqId\x12#\n" +
	"\ractivity_type\x18\x02 \x01(\tR\factivityType\x12\x14\n" +
	"\x05input\x18\x03 \x01(\fR\x05input\x12\x1d\n" +
	"\n" +
	"task_queue\x18\x04 \x01(\tR\ttaskQueue\x12N\n" +
	"\x16start_to_close_timeout\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\x13startToCloseTimeout\x12>\n" +
	"\fretry_policy\x18\x06 \x01(\v2\x1b.dandori.api.v1.RetryPolicyR\vretryPolicy\x12F\n" +
	"\x11heartbeat_timeout\x18\a \x01(\v2\x19.google.protobuf.DurationR\x10heartbeatTimeout\x129\n" +
	"\x19schedule_to_close_timeout\x18\b \x01(\x03R\x16scheduleToCloseTimeout\x129\n" +
	"\x19schedule_to_start_timeout\x18\t \x01(\x03R\x16scheduleToStartTimeout\"4\n" +
	"\x1aCompleteWorkflowAttributes\x12\x16\n" +
	"\x06result\x18\x01 \x01(\fR\x06result\"=\n" +
	"\x16FailWorkflowAttributes\x12#\n" +
	"\rerror_message\x18\x01 \x01(\tR\ferrorMessage\"\xe5\x01\n" +
	"\vRetryPolicy\x12!\n" +
	"\fmax_attempts\x18\x01 \x01(\x05R\vmaxAttempts\x12D\n" +
	"\x10initial_interval\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x0finitialInterval\x12/\n" +
	"\x13backoff_coefficient\x18\x03 \x01(\x01R\x12backoffCoefficient\x12<\n" +
	"\fmax_interval\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\vmaxInterval\"d\n" +
	"\x14StartTimerAttributes\x12\x15\n" +
	"\x06seq_id\x18\x01 \x01(\x03R\x05seqId\x125\n" +
	"\bduration\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\bduration\".\n" +
	"\x15CancelTimerAttributes\x12\x15\n" +
	"\x06seq_id\x18\x01 \x01(\x03R\x05seqId\"d\n" +
	"\x0fActivityFailure\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12#\n" +
	"\rnon_retryable\x18\x03 \x01(\bR\fnonRetryable\"\xb0\x01\n" +
	"\x1cStartChildWorkflowAttributes\x12\x15\n" +
	"\x06seq_id\x18\x01 \x01(\x03R\x05seqId\x12\x1f\n" +
	"\vworkflow_id\x18\x02 \x01(\tR\n" +
	"workflowId\x12#\n" +
	"\rworkflow_type\x18\x03 \x01(\tR\fworkflowType\x12\x1d\n" +
	"\n" +
	"task_queue\x18\x04 \x01(\tR\ttaskQueue\x12\x14\n" +
	"\x05input\x18\x05 \x01(\fR\x05input\"I\n" +
	"\x1aRecordSideEffectAttributes\x12\x15\n" +
	"\x06seq_id\x18\x01 \x01(\x03R\x05seqId\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value\"s\n" +
	"\x17ContinueAsNewAttributes\x12#\n" +
	"\rworkflow_type\x18\x01 \x01(\tR\fworkflowType\x12\x1d\n" +
	"\n" +
	"task_queue\x18\x02 \x01(\tR\ttaskQueue\x12\x14\n" +
	"\x05input\x18\x03 \x01(\fR\x05input\"^\n" +
	"\fPendingQuery\x12\x19\n" +
	"\bquery_id\x18\x01 \x01(\x03R\aqueryId\x12\x1d\n" +
	"\n" +
	"query_type\x18\x02 \x01(\tR\tqueryType\x12\x14\n" +
	"\x05input\x18\x03 \x01(\fR\x05input\"S\n" +
	"\x1aWorkflowSignaledAttributes\x12\x1f\n" +
	"\vsignal_name\x18\x01 \x01(\tR\n" +
	"signalName\x12\x14\n" +
	"\x05input\x18\x02 \x01(\fR\x05input*\x94\x02\n" +
	"\x17WorkflowExecutionStatus\x12)\n" +
	"%WORKFLOW_EXECUTION_STATUS_UNSPECIFIED\x10\x00\x12%\n" +
	"!WORKFLOW_EXECUTION_STATUS_RUNNING\x10\x01\x12'\n" +
	"#WORKFLOW_EXECUTION_STATUS_COMPLETED\x10\x02\x12$\n" +
	" WORKFLOW_EXECUTION_STATUS_FAILED\x10\x03\x12(\n" +
	"$WORKFLOW_EXECUTION_STATUS_TERMINATED\x10\x04\x12.\n" +
	"*WORKFLOW_EXECUTION_STATUS_CONTINUED_AS_NEW\x10\x05*\xee\x02\n" +
	"\vCommandType\x12\x1c\n" +
	"\x18COMMAND_TYPE_UNSPECIFIED\x10\x00\x12'\n" +
	"#COMMAND_TYPE_SCHEDULE_ACTIVITY_TASK\x10\x01\x12\"\n" +
	"\x1eCOMMAND_TYPE_COMPLETE_WORKFLOW\x10\x02\x12\x1e\n" +
	"\x1aCOMMAND_TYPE_FAIL_WORKFLOW\x10\x03\x12\x1c\n" +
	"\x18COMMAND_TYPE_START_TIMER\x10\x04\x12\x1d\n" +
	"\x19COMMAND_TYPE_CANCEL_TIMER\x10\x05\x12#\n" +
	"\x1fCOMMAND_TYPE_RECORD_SIDE_EFFECT\x10\x06\x12%\n" +
	"!COMMAND_TYPE_START_CHILD_WORKFLOW\x10\a\x12 \n" +
	"\x1cCOMMAND_TYPE_CONTINUE_AS_NEW\x10\t\x12)\n" +
	"%COMMAND_TYPE_UPSERT_SEARCH_ATTRIBUTES\x10\n" +
	"B*Z(github.com/asakaida/dandori/api/v1;apiv1b\x06proto3"

var (
	file_api_v1_types_proto_rawDescOnce sync.Once
	file_api_v1_types_proto_rawDescData []byte
)

func file_api_v1_types_proto_rawDescGZIP() []byte {
	file_api_v1_types_proto_rawDescOnce.Do(func() {
		file_api_v1_types_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_v1_types_proto_rawDesc), len(file_api_v1_types_proto_rawDesc)))
	})
	return file_api_v1_types_proto_rawDescData
}

var file_api_v1_types_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_v1_types_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_api_v1_types_proto_goTypes = []any{
	(WorkflowExecutionStatus)(0),           // 0: dandori.api.v1.WorkflowExecutionStatus
	(CommandType)(0),                       // 1: dandori.api.v1.CommandType
	(*WorkflowExecution)(nil),              // 2: dandori.api.v1.WorkflowExecution
	(*HistoryEvent)(nil),                   // 3: dandori.api.v1.HistoryEvent
	(*Command)(nil),                        // 4: dandori.api.v1.Command
	(*ScheduleActivityTaskAttributes)(nil), // 5: dandori.api.v1.ScheduleActivityTaskAttributes
	(*CompleteWorkflowAttributes)(nil),     // 6: dandori.api.v1.CompleteWorkflowAttributes
	(*FailWorkflowAttributes)(nil),         // 7: dandori.api.v1.FailWorkflowAttributes
	(*RetryPolicy)(nil),                    // 8: dandori.api.v1.RetryPolicy
	(*StartTimerAttributes)(nil),           // 9: dandori.api.v1.StartTimerAttributes
	(*CancelTimerAttributes)(nil),          // 10: dandori.api.v1.CancelTimerAttributes
	(*ActivityFailure)(nil),                // 11: dandori.api.v1.ActivityFailure
	(*StartChildWorkflowAttributes)(nil),   // 12: dandori.api.v1.StartChildWorkflowAttributes
	(*RecordSideEffectAttributes)(nil),     // 13: dandori.api.v1.RecordSideEffectAttributes
	(*ContinueAsNewAttributes)(nil),        // 14: dandori.api.v1.ContinueAsNewAttributes
	(*PendingQuery)(nil),                   // 15: dandori.api.v1.PendingQuery
	(*WorkflowSignaledAttributes)(nil),     // 16: dandori.api.v1.WorkflowSignaledAttributes
	nil,                                    // 17: dandori.api.v1.WorkflowExecution.SearchAttributesEntry
	(*timestamppb.Timestamp)(nil),          // 18: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),            // 19: google.protobuf.Duration
}
var file_api_v1_types_proto_depIdxs = []int32{
	0,  // 0: dandori.api.v1.WorkflowExecution.status:type_name -> dandori.api.v1.WorkflowExecutionStatus
	18, // 1: dandori.api.v1.WorkflowExecution.created_at:type_name -> google.protobuf.Timestamp
	18, // 2: dandori.api.v1.WorkflowExecution.updated_at:type_name -> google.protobuf.Timestamp
	18, // 3: dandori.api.v1.WorkflowExecution.closed_at:type_name -> google.protobuf.Timestamp
	17, // 4: dandori.api.v1.WorkflowExecution.search_attributes:type_name -> dandori.api.v1.WorkflowExecution.SearchAttributesEntry
	18, // 5: dandori.api.v1.HistoryEvent.timestamp:type_name -> google.protobuf.Timestamp
	1,  // 6: dandori.api.v1.Command.type:type_name -> dandori.api.v1.CommandType
	19, // 7: dandori.api.v1.ScheduleActivityTaskAttributes.start_to_close_timeout:type_name -> google.protobuf.Duration
	8,  // 8: dandori.api.v1.ScheduleActivityTaskAttributes.retry_policy:type_name -> dandori.api.v1.RetryPolicy
	19, // 9: dandori.api.v1.ScheduleActivityTaskAttributes.heartbeat_timeout:type_name -> google.protobuf.Duration
	19, // 10: dandori.api.v1.RetryPolicy.initial_interval:type_name -> google.protobuf.Duration
	19, // 11: dandori.api.v1.RetryPolicy.max_interval:type_name -> google.protobuf.Duration
	19, // 12: dandori.api.v1.StartTimerAttributes.duration:type_name -> google.protobuf.Duration
	13, // [13:13] is the sub-list for method output_type
	13, // [13:13] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_api_v1_types_proto_init() }
func file_api_v1_types_proto_init() {
	if File_api_v1_types_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_v1_types_proto_rawDesc), len(file_api_v1_types_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_v1_types_proto_goTypes,
		DependencyIndexes: file_api_v1_types_proto_depIdxs,
		EnumInfos:         file_api_v1_types_proto_enumTypes,
		MessageInfos:      file_api_v1_types_proto_msgTypes,
	}.Build()
	File_api_v1_types_proto = out.File
	file_api_v1_types_proto_goTypes = nil
	file_api_v1_types_proto_depIdxs = nil
}
